title: Przemek Sobstel
url: "https://www.sobstel.dev" # the base hostname & protocol for your site

exclude: ["Rakefile", "Gemfile", "stuff"]
markdown: kramdown

permalink: /blog/:title/

# collections:
#   gists:
#     output: true
#     permalink: /gists/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "legacy"

port: 1982

plugins:
  - jekyll-redirect-from

sass:
  style: compressed
